#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: app-front-volume-pv
#  labels:
#    type: local
#spec:
#  storageClassName: generic
#  capacity:
#    storage: 100Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "front"
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  creationTimestamp: null
#  name: app-front-volume-pvc
#spec:
#  storageClassName: generic
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Mi
#status: {}
#
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
  labels:
    app: appmoneaz
    role: front
spec:
  selector:
    matchLabels:
      app: appmoneaz
      role: front
  template:
    metadata:
      labels:
        app: appmoneaz
        role: front
    spec:
      restartPolicy: Always
      containers:
        - name: front
          image: moneaz-app_angular-ui
          imagePullPolicy: "IfNotPresent"
          resources:
#            limits:
#              memory: "1Gi"
#              cpu: "500m"
            requests:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 4200
#          volumeMounts:
#            - name: app-front-volume
#              mountPath: /usr/src/app/app-ui
#      volumes:
#        - name: app-front-volume
#          persistentVolumeClaim:
#            claimName: app-front-volume-pvc