apiVersion: v1
kind: Service
metadata:
  name: app-front
  labels:
    app: appmoneaz
    role: front
spec:
  selector:
    app: appmoneaz
    role: front
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 31014
  loadBalancerIP: 127.0.0.1
