FROM node:10

WORKDIR /usr/src/app/app-ui

COPY ./front/package*.json ./

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

COPY ./front/ ./

ARG front_env

ENV front_env=$front_env

CMD npm start -- --configuration=${front_env}
